<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GuitarFlashCards.Android</RootNamespace>
    <ApplicationTitle>Guitar Flash Cards</ApplicationTitle>
    <ApplicationId>com.guitarflashcards.mobile</ApplicationId>
    <ApplicationVersion>3</ApplicationVersion>
    <ApplicationDisplayVersion>1.2</ApplicationDisplayVersion>
    <RuntimeIdentifiers>android-arm;android-arm64;android-x64</RuntimeIdentifiers>
    <!--
      Enables trim analyzers and full trimming during Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
    <TrimMode>full</TrimMode>
  </PropertyGroup>
  <ItemGroup>
    <AndroidJavaSource Remove="bin\Debug\**" />
    <AndroidLibrary Remove="bin\Debug\**" />
    <AndroidNativeLibrary Remove="bin\Debug\**" />
    <Compile Remove="bin\Debug\**" />
    <EmbeddedResource Remove="bin\Debug\**" />
    <JavaSourceJar Remove="bin\Debug\**" />
    <None Remove="bin\Debug\**" />
    <ProguardConfiguration Remove="bin\Debug\**" />
    <TransformFile Remove="bin\Debug\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="bin\Release\net10.0-android\GuitarFlashCards.Android.runtimeconfig.json" />
    <Content Include="bin\Release\net10.0-android\GuitarFlashCards.Android.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="bin\Release\net10.0-android\com.guitarflashcards.mobile-Signed.aab" />
    <None Include="bin\Release\net10.0-android\com.guitarflashcards.mobile-Signed.apk" />
    <None Include="bin\Release\net10.0-android\com.guitarflashcards.mobile.aab" />
    <None Include="bin\Release\net10.0-android\GuitarFlashCards.Android.dll" />
    <None Include="bin\Release\net10.0-android\GuitarFlashCards.Android.pdb" />
  </ItemGroup>
</Project>
